apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: my-java-jar-runner
  platformProvider: my-kubernetes
  labels:
    env: demo
    type: external-runtime
  description: "Demonstrates using SCRIPT_RUN stages to manage a non-Kubernetes app (Docker container or raw JAR)"
  planner:
    alwaysUsePipeline: true
  
  input:
    manifests:
      - configmap.yaml
    kubectlVersion: 1.32.2
  pipeline:
    stages:
      - name: SCRIPT_RUN
        desc: Stop old process / container if running
        with:
          env:
            STEP: stop
          run: |
            ./scripts/stop.sh
      - name: SCRIPT_RUN
        desc: Fetch new artifact (download jar or pull image)
        with:
          env:
            STEP: fetch
          run: |
            ./scripts/fetch.sh
      - name: SCRIPT_RUN
        desc: Start new process
        with:
          env:
            STEP: start
          run: |
            ./scripts/start.sh
          onRollback: |
            echo "[PIPELINE] Rolling back -> restarting previous version";
            ./scripts/start.sh rollback