apiVersion: pipecd.dev/v1beta1
kind: GenericApplication
spec:
  name: my-java-app
  pipeline:
    stages:
      - name: StopOldApp
        kind: SCRIPT_RUN
        with:
          script: ./scripts/stop.sh

      - name: FetchArtifact
        kind: SCRIPT_RUN
        with:
          script: ./scripts/fetch.sh

      - name: StartNewApp
        kind: SCRIPT_RUN
        with:
          script: ./scripts/start.sh
        onRollback:
          # rollback nếu start fail → quay lại bản cũ
          script: ./scripts/start.sh rollback