apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-demo
  labels:
    app: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green-demo
        image: nginx:1.21
        ports:
        - containerPort: 80
