apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-service
spec:
  selector:
    app: green # Chuyển sang app: blue để chuyển traffic về blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
